apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apps.app.learn.com
spec:
  group: app.learn.com
  names:
    kind: App
    listKind: AppList
    plural: apps
    singular: app
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: App is the Schema for the apps API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AppSpec defines the desired state of App
          properties:
            image:
              description: image
              type: string
            name:
              description: name
              type: string
            replicas:
              description: replicas
              type: integer
          required:
          - image
          - name
          - replicas
          type: object
        status:
          description: AppStatus defines the observed state of App
          properties:
            podNames:
              description: pod name list
              items:
                type: string
              type: array
            replicas:
              description: replicas
              type: integer
          required:
          - podNames
          - replicas
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
